In [31]:
# utilizado para la manipulación de directorios y rutas
import os

# Cálculo científico y vectorial para python
import numpy as np

# Libreria para graficos
from matplotlib import pyplot

# Modulo de optimizacion en scipy
from scipy import optimize

import pandas as pd

In [32]:
data1 = pd.read_csv('anemia.csv', header = None)
data1

         0           1       2                   3       4               5
0       NO    LAB_TEST  RESULT  REFERENCE_INTERVAL  GENDER  IDENTIFICATION
1        1  Hemoglobin    14.9         13.5 - 17.5    Male      Not Anemia
2        1         MCH    22.7         27.0 - 31.0    Male      Not Anemia
3        1        MCHC    29.1         32.0 - 36.0    Male      Not Anemia
4        1         MCV    83.7         82.0 - 92.0    Male      Not Anemia
...    ...         ...     ...                 ...     ...             ...
5680  1420         MCV    95.2         82.0 - 92.0  Female      Not Anemia
5681  1421  Hemoglobin    11.8         12.0 - 16.0  Female          Anemia
5682  1421         MCH    21.2         27.0 - 31.0  Female          Anemia
5683  1421        MCHC    28.4         32.0 - 36.0  Female          Anemia
5684  1421         MCV    98.1         82.0 - 92.0  Female          Anemia

[5685 rows x 6 columns]

In [33]:
#Cambio los valores
data1.iloc[:,1].replace('Hemoglobin', 1,inplace=True)
data1.iloc[:,1].replace('MCH', 2,inplace=True)
data1.iloc[:,1].replace('MCHC', 3,inplace=True)
data1.iloc[:,1].replace('MCV', 4,inplace=True)

data1.iloc[:,4].replace('Male', 0,inplace=True)
data1.iloc[:,4].replace('Female', 1,inplace=True)

data1.iloc[:,5].replace('Not Anemia', 0,inplace=True)
data1.iloc[:,5].replace('Anemia', 1,inplace=True)

data1

         0         1       2                   3       4               5
0       NO  LAB_TEST  RESULT  REFERENCE_INTERVAL  GENDER  IDENTIFICATION
1        1         1    14.9         13.5 - 17.5       0               0
2        1         2    22.7         27.0 - 31.0       0               0
3        1         3    29.1         32.0 - 36.0       0               0
4        1         4    83.7         82.0 - 92.0       0               0
...    ...       ...     ...                 ...     ...             ...
5680  1420         4    95.2         82.0 - 92.0       1               0
5681  1421         1    11.8         12.0 - 16.0       1               1
5682  1421         2    21.2         27.0 - 31.0       1               1
5683  1421         3    28.4         32.0 - 36.0       1               1
5684  1421         4    98.1         82.0 - 92.0       1               1

[5685 rows x 6 columns]

In [34]:
data = np.array(data1)
x = data[0:5000, 0:5]
y = data[0:5000, 5]
m =y.size
print(x.shape)
print(y.shape)

(5000, 5)
(5000,)

In [35]:
def  featureNormalize(x):
    X_norm = X.copy()
    mu = np.zeros(X.shape[1])
    sigma = np.zeros(X.shape[1])

    mu = np.mean(X, axis = 0)
    sigma = np.std(X, axis = 0)
    X_norm = (x - mu) / sigma
    
    return X_norm, mu, sigma

In [36]:
def sigmoid(z):
    # Calcula la sigmoide de una entrada z
    # convierte la intrada a un arreglo numpy
    z = np.array(z)
  
    g = np.zeros(z.shape)

    g = 1 / (1 + np.exp(-z))

    return g

In [37]:
# Prueba la implementacion de la funcion sigmoid
z = 21
g = sigmoid(z)

print('g(', z, ') = ', g)

g( 21 ) =  0.9999999992417439

In [38]:
# Configurar la matriz adecuadamente, y agregar una columna de unos que corresponde al termino de intercepción. 
m, n = x.shape
# Agraga el termino de intercepción a A
x = np.concatenate([np.ones((m, 1)), x], axis=1)

print(x[:])

[[1.0 'NO' 'LAB_TEST' 'RESULT' 'REFERENCE_INTERVAL' 'GENDER']
 [1.0 '1' 1 '14.9' '13.5 - 17.5' 0]
 [1.0 '1' 2 '22.7' '27.0 - 31.0' 0]
 ...
 [1.0 '1250' 1 '13.2' '12.0 - 16.0' 1]
 [1.0 '1250' 2 '23.8' '27.0 - 31.0' 1]
 [1.0 '1250' 3 '28' '32.0 - 36.0' 1]]

In [39]:
def calcularCosto(theta, X, y):
    # Inicializar algunos valores utiles
    m = y.size  # numero de ejemplos de entrenamiento

    J = 0
    h = calcularSigmoide(X.dot(theta.T))
    J = (1 / m) * np.sum(-y.dot(np.log(h)) - (1 - y).dot(np.log(1 - h)))
    return J

In [40]:
def descensoGradiente(theta, X, y, alpha, num_iters):
    # Inicializa algunos valores
    m = y.shape[0] # numero de ejemplos de entrenamiento
    
    # realiza una copia de theta, el cual será acutalizada por el descenso por el gradiente
    theta = theta.copy()
    J_history = []
    
    for i in range(num_iters):
        h = sigmoid(X.dot(theta.T))
        theta = theta - (alpha / m) * (h - y).dot(X)
       
        J_history.append(calcularCosto(theta, X, y))
    return theta, J_history

In [41]:
# Elegir algun valor para alpha (probar varias alternativas)
alpha = 0.0001
num_iters = 10000

# inicializa theta y ejecuta el descenso por el gradiente
theta = np.zeros(6)
theta, J_history = descensoGradiente(theta, x, y, alpha, num_iters)

# Muestra los resultados del descenso por el gradiente
print('theta calculado por el descenso por el gradiente: {:s}'.format(str(theta)))

TypeError: can't multiply sequence by non-int of type 'float'

In [ ]:
# Grafica la convergencia del costo
pyplot.plot(np.arange(len(J_history)), J_history, lw=2)
pyplot.xlabel('Numero de iteraciones')
pyplot.ylabel('Costo J')
Costo = J_history[-1]
print("Valor del costo inicial : ",cost)
print("Valor del costo final : ",Costo)

In [ ]:
# verificar si el tumor es benigno(0) o maligno(1)
# datos no utilizados de la tabla para la prediccion
# segun la tabla con estos datos un tumor es maligno
X_array = [1, 5.0,	10.0,	10.0,	3.0,	7.0,	3.0,	8.0,	10.0,	2.0]
prueba = calcularSigmoide(np.dot(X_array, theta))
print(f"Basandonos en los analisis podemos deducir que el tumor es (usando el descenso por el gradiente):{prueba}") #correcto

# segun la tabla con estos datos un tumor es benigno
X_array = [1, 2.0,	1.0,	1.0,	1.0,	2.0,	1.0,	1.0,	1.0,	1.0]
prueba2 = calcularSigmoide(np.dot(X_array, theta))
print(f"Basandonos en los analisis podemos deducir que el tumor es (usando el descenso por el gradiente):{prueba2}") #correcto